name: Call a reusable workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  call-workflow:
    uses: vusal-Org/cronjobProject/.github/workflows/workflow-A.yml@main
