name: Pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pr-opened:
    if: github.event_name == 'pull_request'
    uses: vusal-Org/cronjobProject/.github/workflows/pr-opened.yml@main
  pr-merged:
    if: github.event_name == 'push'
    uses: vusal-Org/cronjobProject/.github/workflows/pr-merged.yml@main
